// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD10lkR-LkysU8h3PPMA8sndD4s-L5rNJ4',
    appId: '1:283943969544:web:13753c89d6873aba9c42bd',
    messagingSenderId: '283943969544',
    projectId: 'registeration-aef8d',
    authDomain: 'registeration-aef8d.firebaseapp.com',
    storageBucket: 'registeration-aef8d.appspot.com',
    measurementId: 'G-0Z327RCBX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqrv3ioZ318KJGiNqPeexDUHPkYuVZgo',
    appId: '1:283943969544:android:f785fe63838787f29c42bd',
    messagingSenderId: '283943969544',
    projectId: 'registeration-aef8d',
    storageBucket: 'registeration-aef8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzC0vzCJu9711M-L9_cNDyROo4ZDjPcw',
    appId: '1:283943969544:ios:142b8450b8aeb2649c42bd',
    messagingSenderId: '283943969544',
    projectId: 'registeration-aef8d',
    storageBucket: 'registeration-aef8d.appspot.com',
    iosBundleId: 'com.example.registeration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzC0vzCJu9711M-L9_cNDyROo4ZDjPcw',
    appId: '1:283943969544:ios:0136522cc0a542999c42bd',
    messagingSenderId: '283943969544',
    projectId: 'registeration-aef8d',
    storageBucket: 'registeration-aef8d.appspot.com',
    iosBundleId: 'com.example.registeration.RunnerTests',
  );
}
